### PR TITLE
Feature/new select

### LINKED ISSUE #70: Fix select list on Population Card
screen shot 2017-07-02 at 11 06 34 am

The current dropdown has two down arrows, and is fairly small.

There is a [storybook dropdown](https://hackoregon.github.io/component-library/?knob-Amount%20of%20data%20values=3&knob-Array%20of%20colors%5B0%5D=%23a6cee3&knob-Array%20of%20colors%5B1%5D=%231f78b4&knob-Array%20of%20colors%5B2%5D=%23b2df8a&knob-Chart%20Width%20and%20Height=%7B%22width%22%3A600%2C%22height%22%3A250%7D&knob-Title%20text=Some%20title&knob-Subtitle%20text=Some%20subtitle&knob-Title%20font%20size=24&knob-Subtitle%20font%20size=14&knob-Inner%20Radius=75&selectedKind=Dropdown&selectedStory=Simple%20usage&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel) - use this for consistency. (Note that the storybook dropdown has a double outline, which looks a little funky...but less funky than our current dropdown)

### PR DESCRIPTION
**Pull request by clemf**
I was only trying to add the dropdown component, but the CSS wouldn't work. I ended up copying the working system from the Housing team. Now CSS seems to work! Yay! I also got the Dropdown to work for us!

Fixes #70

### CODE REVIEW

**Comment by clemf** [comment]
This appears to have failed to build on prod. @meganmckissack halp I don't know what I'm doing.

**Comment by MikeTheCanuck** [comment]
Hey @clemf I had a look around, nothing obvious about the TravisCI config or the way the repo is setup, but in googling the operation I came across this SO article:
https://stackoverflow.com/questions/39140800/the-command-eval-git-fetch-origin-refs-pull-7-merge-failed

It sounds like the same circumstances and though I don't recall TravisCI behaviours like this, it makes some sense that if the build is looking for the code in the originally-submitted branch, that the build will fail if the branch gets deleted before the build has cloned the source files.

I've never encountered this behaviour myself, because every time I merged a branch I was so fixated on seeing whether the build succeeded that I never deleted the branch until long after the build had successfully deployed.

I don't know of an obvious way to rehydrate a deleted branch, but if you know of any advanced technique like that, it's worth a shot to resurrect the missing branch and restart the failed build.

Or alternatively, you could try committing a trivial change to the current master branch and see if that builds and deploys.

**Comment by clemf** [comment]
@MikeTheCanuck Thanks for looking at it for me. I guess I have been merging before the Travis build succeeds. I'm doubtful that is the problem because I've done it before with no issues. I think it's more likely because the branch I merged changed some of the build config. Maybe it has to do with the linter errors? I think I may have re-enabled the linter during the build process. I'm going to try to fix the linter errors and see if that helps.

**Comment by MikeTheCanuck** [comment]
Howdy @clemf - merging isn't an issue AFAIK, but it appears from the results for this build, and for the linked issue I noted, deleting the branch before the build is completed can prevent TravisCI from performing the `git fetch`.  Is it possible you immediately deleted the branch (in your fork) from which you merged?  I can't find it in your forked repo now, and the timestamps noted in the pull request are suggestive that the branch was deleted around the same time as the merge, and missing code could account for the failed `git fetch` around lines 144-148 of [the build](https://travis-ci.org/hackoregon/teamHomelessness-frontend/jobs/249832011).  It's news to me that Travis chases the origin when pulling a commit, but I'll trust the evidence as it emerges.  Hope this helps.  Happy to investigate future builds to help keep this working.

**Comment by meganmckissack** [comment]
Hey @clemf , I started poking around the issue and will continue tomorrow but one thing I remembered is that David changed the housing repo to using webpack 2 during the days immediately following demo day, while all the other repos are still the same.  One of our biggest problems getting any build to show up, hence why we had to do some webpack hacking, was that the css loaders weren't working as expected.  I don't know if this affects this issues you're having but I'm guessing that it's probably related.

**Pull request merged**
